---
version: "3"

services:
  backend:
    image: festapi-without-redis
    build:
      context: "./backend"
      dockerfile: "./Dockerfile"
    volumes:
      - "tmp:/home/project/app/__pycache__"
      - "./backend/app:/home/project/app"
    ports:
      - "82:9999"
    container_name: backend

volumes:
  tmp:
...
